services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: synapsecity-api-gateway
    ports:
      - "9000:9000"
    environment:
      BACKEND_BASE_URL: http://backend:8000
      FLEET_BASE_URL: http://fleet-service:8080
    depends_on:
      - backend
      - fleet-service

  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    container_name: synapsecity-admin-dashboard
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: synapsecity-backend
    ports:
      - "8000:8000"
    environment:
      EMERGENCY_API_TOKEN: synapse-emergency-token
      PREDICTION_ENGINE_TOKEN: synapse-prediction-token
      POLLUTION_AQI_THRESHOLD: "150"
      POLLUTION_PM25_THRESHOLD: "55"
      POLLUTION_NO2_THRESHOLD: "100"
    depends_on:
      - mosquitto
      - redis
      - postgres
      - influxdb

  fleet-service:
    build:
      context: ./fleet-service
      dockerfile: Dockerfile
    container_name: synapsecity-fleet-service
    ports:
      - "8080:8080"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: synapsecity-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  redis:
    image: redis:7
    container_name: synapsecity-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: synapsecity-postgres
    environment:
      POSTGRES_DB: synapsecity
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: synapse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.7
    container_name: synapsecity-influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: synapse
      DOCKER_INFLUXDB_INIT_PASSWORD: synapse123
      DOCKER_INFLUXDB_INIT_ORG: synapse-city
      DOCKER_INFLUXDB_INIT_BUCKET: traffic_analytics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: synapse-influx-token
    volumes:
      - influxdb_data:/var/lib/influxdb2

  prediction-engine:
    build:
      context: ./prediction-engine
      dockerfile: Dockerfile
    container_name: synapsecity-prediction-engine
    ports:
      - "9100:9100"
    environment:
      BACKEND_BASE_URL: http://backend:8000
      PREDICTION_ENGINE_TOKEN: synapse-prediction-token
      INFLUX_URL: http://influxdb:8086
      INFLUX_ORG: synapse-city
      INFLUX_BUCKET: traffic_analytics
      INFLUX_TOKEN: synapse-influx-token
      MODEL_UPDATE_INTERVAL_SECONDS: "300"
      HIGH_CONGESTION_THRESHOLD: "30"
    depends_on:
      - backend
      - influxdb

volumes:
  postgres_data:
  influxdb_data:
