services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: synapsecity-api-gateway
    ports:
      - "9000:9000"
    environment:
      BACKEND_BASE_URL: http://backend:8000
      FLEET_BASE_URL: http://fleet-service:8080
    depends_on:
      - backend
      - fleet-service

  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    container_name: synapsecity-admin-dashboard
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: synapsecity-backend
    ports:
      - "8000:8000"
    environment:
      EMERGENCY_API_TOKEN: synapse-emergency-token
      POLLUTION_AQI_THRESHOLD: "150"
      POLLUTION_PM25_THRESHOLD: "55"
      POLLUTION_NO2_THRESHOLD: "100"
    depends_on:
      - mosquitto
      - redis
      - postgres

  fleet-service:
    build:
      context: ./fleet-service
      dockerfile: Dockerfile
    container_name: synapsecity-fleet-service
    ports:
      - "8080:8080"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: synapsecity-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  redis:
    image: redis:7
    container_name: synapsecity-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: synapsecity-postgres
    environment:
      POSTGRES_DB: synapsecity
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: synapse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
